### ISSUE TITLE
Syntax error on Windows

### ISSUE THREAD

**Issue by kgryte** [ForbesLindesay/cmd-shim#17]
This issue seems to be related to #16, and possibly to the change introduced in #4 by @copenhas. 

## Description

Running Windows builds on AppVeyor with MinGW and MSYS. When executing test commands of the sort,

``` bash
/c/projects/foo/node_modules/.bin/istanbul cover \
  --no-default-excludes \
  -x 'node_modules/**' \
  -x 'build/**' \
  -x '**/test/**' \
  -x '**/tests/**' \
  -x 'reports/**' \
  --dir /c/projects/foo/reports/coverage \
  --report lcov \
  /c/projects/foo/node_modules/.bin/tape -- /c/projects/foo/test/test.js /c/projects/foo/test/test.a.js
```

I encounter the following error

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
 
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Object.Module._extensions.(anonymous function) [as .js] (c:\projects\foo\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at runFn (c:\projects\foo\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at c:\projects\foo\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at c:\projects\foo\node_modules\istanbul\lib\util\file-matcher.js:68:16
make[1]: *** [test-istanbul] Error 1
make[1]: Leaving directory `/c/projects/foo'
make: *** [test-cov] Error 2
```

## Environments

OS:
* Windows

Node/npm versions:
* 5.10.1 / 2.8.3
* 4.4.2 / 2.15.0
* 0.12.13 / 2.15.0 
* 0.10.44 / 2.15.0

##  Notes

* I am able to run other commands, such as 

    ``` bash
    /c/projects/foo/node_modules/.bin/tape /c/projects/foo/test/test.js /c/projects/foo/test/test.a.js
    ```

* I tried to track down where this line

    ``` bash
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    ```

    occurs in source code. The only place I found was in this dependency, which includes it at [line 135](https://github.com/ForbesLindesay/cmd-shim/blob/3b991770cc03843f9828c1fb9578f57fa4394930/index.js#L135) when creating the Windows shim.

* I am not able to test whether reverting the line in question fixes the problem, as I do not have access to a Windows machine.
* Note that the commands in question run without error on both Mac OS X and Linux Ubuntu, so this is a Windows specific error.

* Similar bugs:
    - bahmutov/pre-git#68
    - coryhouse/react-slingshot#84
    - http://stackoverflow.com/questions/36638181/how-to-setup-basic-api-using-node-on-ripple-network

* Note that the above issues have all been filed post release of [`v2.0.2`](https://github.com/ForbesLindesay/cmd-shim/commit/75edc98dec188cca8b819865699a2eaa5e41afae) which included #4.

**Comment by copenhas** [comment]
Sorry for such a late response. I don't have a Windows setup at home. I got a basic setup going and tried something real quick.

Setup:

    Windows 7
    git for Windows 2.8.1
    node 4.4.3
    MinGW with MSYS installed (grabbed the installer from sourceforge)

I installed istanbul globally:

    npm install -g istanbul

Then in git bash, cmd.exe, and MSYS bash this is what I got:

    $ istanbul
    Need a command to run
    Try "istanbul help" for usage

Just to make sure the line in question was in the script I ran the following in git bash:

```bash
$ cat `which istanbul`
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/istanbul/lib/cli.js" "$@"
  ret=$?
else
  node  "$basedir/node_modules/istanbul/lib/cli.js" "$@"
  ret=$?
fi
exit $ret
```

Looks like this needs some more investigation to figure out why this is causing issues for you. I'll try to test some git extensions at work when I get a chance (it might take me a few days though). They were the reason originally #4 was opened.

**Comment by kgryte** [comment]
@copenhas Thanks for the response. Might be worth trying to run some of the `istanbul` commands (e.g., `istanbul cover`) to see if things work on your end. And would there be any difference in a local installation as opposed to installing globally? Also, not sure if this is an `istanbul` specific issue.

**Comment by khelmar** [comment]
I'm seeing the same issue when trying to run `sass-lint` so I don't think it's `istanbul` specific

**Comment by kgryte** [comment]
@copenhas wanted to follow-up and see if you had any updates.

**Comment by pallxk** [comment]
Out of curiosity, I made some investigation on this.

In fact, `SyntaxError: missing ) after argument list` is reported by node.js and is not reported by shell. So this does not necessarily mean something goes wrong with the shim shell script.

With some reading of the code of `istanbul` and testing, I think this is **caused by running the shim shell script via node**. That is, in your particular case, `node /c/projects/foo/node_modules/.bin/tape` was run under the hood, where `./bin/tap` is the shim shell script rather than the actual node.js script. You may check this with `--verbose` added to your `istanbul cover` command.

See [istanbul/run-with-cover.js#L117](https://github.com/gotwarlost/istanbul/blob/master/lib/command/common/run-with-cover.js#L117) for related code.

So even if this is not `istanbul` specific, I thinks it's not caused by #4, and not related to #16.

(I'm new to node.js and not using `istanbul`, so chances are I missed or misunderstood something. Please tell me if i'm wrong.)

**Comment by copenhas** [comment]
I have not had a chance to look into again. I'm afraid I got caught up with work long enough to forget about this issue. I apologize. 

I did test out our internal git extensions (written in node and the reason I submitted #4 ), and they work on latest node.js. After reading @pallxk comment (thanks for looking into it), I looked at the Istanbul documentation [here](https://github.com/gotwarlost/istanbul#the-cover-command). It looks like the command is expecting a node.js javascript file and not a shell command. 

Perhaps instead of passing istanbul `/c/projects/foo/node_modules/.bin/tape` you could try figuring out what the main module is and pass it that. Based on tape's [package.json](https://github.com/substack/tape/blob/master/package.json#L5) it looks like it would be something like this: `/c/projects/foo/node_modules/tape/main.js`.

**Comment by kdawg1406** [comment]
I've got the exact same issue, driving me crazy.  The same exact code runs on my Mac w/o this error, but on Windows it just won't run.

Don't have any idea where to start looking.

**Comment by copenhas** [comment]
@kdawg1406 I believe the difference between macOS and Windows is that macOS supports she-bang scripts, while in Windows the commands have to wrapped up into the cmd shim. So when you pass in `./node_modules/.bin/mocha` on macOS the file probably contains JavaScript, but on Windows it contains shell commands.

Per the comments above you'll find that Istanbul is actually expecting a JavaScript file as the argument and not shell script or command. I believe that's what's causing the syntax error for you. You'll need to find out what the main module file path is so you can pass it in cross platform.

**Comment by copenhas** [comment]
Looks like Istanbul documents it some at [README.md#usage-on-windows]( https://github.com/gotwarlost/istanbul#usage-on-windows)

**Comment by kdawg1406** [comment]
@copenhas Bingo!

This works for mocha on Windows:

`./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha`

Thank you for your outstanding support and very quick response.

Best to you,

Karl

**Comment by kgryte** [comment]
@copenhas Was able to resolve the issue using a solution similar to the solution described above. Thanks for the help. Closing the issue.

**Comment by ReinsBrain** [comment]
@kdawg1406 - your solution doesn't work for me - when i use: ```./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha```
error is:
```
\node_modules\.bin\_mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```
when i use (as you suggest): ```./node_modules/.bin/istanbul cover ./node_modules/bin/_mocha```
error is: ```Unable to resolve file [./node_modules/bin/_mocha]```

I don't understand how it can't resolve the file because i can see the file at ```./node_modules/bin/_mocha]```

**Comment by kdawg1406** [comment]
@ReinsBrain Not sure, this was a long time ago, so much as changed in the toolchain.  Sorry, I don't have an answer for you.

**Comment by mihaisavezi** [comment]
This doesn't work for storybook. trying to debug via ```node --inspect node_modules/.bin/storybook-start -p 9001```  throws the same error.

**Comment by Sawtaytoes** [comment]
@ReinsBrain You might need to change that line to `npx _mocha`.

Also, this error is happening even in the Webpack project. I get it when I run from a child process started with `node`.

Looks like something these libraries depend on is running this code in a way that Windows doesn't understand.

Whoever wrote the original code (`cmd-shim`?) has an incorrect assumption about the OS when run Node.js runs these commands rather than the OS's CLI.
